# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe59d3a9b83bc2ee6502f1c6980903c57281989e18b053d7545ad15caf2c9c40be10977cf0390cdb9f14884a2c6e4a51604096580697ad37551311b382b3e49e

test:
  secret_key_base: f4a0fd4266a13d30e563aee9f5251bb3ae35fe04e5928e2f8e7ed3f215525b938128d41fadf7e08ed13ca961fa61a163f1e1447e2562924db5a084f4bd337efd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
